version: "3.7"
services:
  httpd:
    image: httpd:2.4.41
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./frontend/app:/app
      - ./frontend/conf:/usr/local/apache2/conf
      - ./logs/front:/logs
  back:
    image: httpd:2.4.41
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes:
      - ./backend/app:/app
      - ./backend/conf:/usr/local/apache2/conf
      - ./logs/back:/logs
    
    depends_on:
      - php
    
  php:
    build:
      context: ./php
    expose: 
      - "9000"
    volumes: 
      - ./backend/app:/app
    
